### ISSUE TITLE
Media in iOS push does not appear to be supported

### ISSUE THREAD

**Issue by isaacwhite** [newsdev/pushkin#7]
I was trying to emulate the localytics payload for rich media to the iOS app and got this validation error back:

> instance.apns.payload.aps additionalProperty "mutable_content" exists in instance when not allowed

Would firebase support us being able to pass through the mutable_content field in aps? That's currently what the iOS app requires to display rich media in the push. The iOS app also requires changing `category` to a value `'c'` instead of `'k'`, but that change did not appear to trigger any validation errors.

**Comment by isaacwhite** [comment]
I also tried this on Android and although validation passes, the image is not displaying in the app. It's possible that additional transforms were taking place behind the scenes with the Localytics API, so I'm curious if there is a way to inspect what the app needs for each of these rich media messages.

**Comment by alastaircoote** [comment]
`mutable_content` actually belongs in `apns.headers`, where it won't throw an error. Otherwise as far as I know you should need to set `ll_attachment_type` to `"image"` and `ll_attachment_url` to the image URL for it to work.

I believe `ll_attachment_url` will also work in Android, there's no reference to `ll_attachment_type` presumably because it can only render images.

**Comment by isaacwhite** [comment]
Paul Yorke reports that setting mutable_content: 1 in the headers does not come through on the iOS end. Could we update the validation so that mutable_content is allowed inside the `apns.payload.aps` object, where he says mutable content needs to appear?

**Comment by isaacwhite** [comment]
Actually, nevermind about iOS rich media issues. I started digging into https://github.com/newsdev/pushkin/blob/master/src/validators/validators.ts, and found that it was expecting a different field name `mutable-content` instead of `mutable_content` in order to pass validation. Using the field name with the dash inside `apns.payload.aps` passes validation and displays correctly in the ios app. Will continue to investigate issues with Android now.

**Comment by isaacwhite** [comment]
Not sure what's changed, but images are coming through on Android today 🎉
